// controllers/authController.js
const Teacher = require("../models/Teacher");
const jwt = require("jsonwebtoken");
const crypto = require('crypto');
const { OAuth2Client } = require('google-auth-library'); // <-- NEW IMPORT
const { sendVerificationEmail, sendPasswordResetEmail } = require("../utils/emailService");

// Initialize Google OAuth2Client with your backend's Google Client ID
// IMPORTANT: Make sure GOOGLE_CLIENT_ID is set in your backend's .env file
const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID); // <-- NEW

// Register a teacher
const register = async (req, res) => {
    try {
        const { email, password } = req.body;

        let teacher = await Teacher.findOne({ email });
        if (teacher) {
            if (!teacher.isVerified) {
                return res.status(400).json({ success: false, message: 'User already exists, but email is not verified. Please check your inbox or try logging in.' });
            }
            return res.status(400).json({ success: false, message: 'User already exists with this email.' });
        }

        teacher = new Teacher({ email, password });

        const verificationToken = teacher.getResetPasswordToken();
        teacher.verificationToken = teacher.resetPasswordToken;
        teacher.resetPasswordToken = undefined;
        teacher.resetPasswordExpires = undefined;

        await teacher.save();

        await sendVerificationEmail(teacher.email, verificationToken);

        res.status(201).json({
            success: true,
            message: "Registration successful! Please check your email to verify your account."
        });

    } catch (error) {
        console.error('Registration error:', error.message);
        res.status(500).json({ success: false, message: 'Server error during registration.' });
    }
};

// Login a teacher
const login = async (req, res) => {
    try {
        const { email, password } = req.body;

        const teacher = await Teacher.findOne({ email });
        if (!teacher) {
            return res.status(404).json({ success: false, message: "User not found." });
        }

        if (!teacher.isVerified) {
            return res.status(401).json({ success: false, message: 'Please verify your email address to log in.' });
        }

        const isMatch = await teacher.comparePassword(password);
        if (!isMatch) {
            return res.status(401).json({ success: false, message: "Invalid credentials." });
        }

        const token = jwt.sign(
            { id: teacher._id },
            process.env.JWT_SECRET,
            { expiresIn: "1h" }
        );

        // For simplicity, sessionCode and userId are placeholders in the frontend.
        // In a real app, you might generate a session code or ensure userId is passed.
        // For now, userId is teacher._id. sessionCode can be a placeholder or generated by socket logic.
        res.status(200).json({
            success: true,
            message: "Logged in successfully!",
            token,
            userId: teacher._id,
            email: teacher.email,
            sessionCode: 'default_session_code' // Placeholder: Adjust as per your session management
        });

    } catch (error) {
        console.error('Login error:', error.message);
        res.status(500).json({ success: false, message: 'Server error during login.' });
    }
};

// --- NEW FUNCTION: Google Login/Registration ---
const googleLogin = async (req, res) => {
    const { idToken } = req.body;

    if (!idToken) {
        return res.status(400).json({ success: false, message: 'Google ID token is required.' });
    }

    try {
        // 1. Verify the ID token with Google
        const ticket = await client.verifyIdToken({
            idToken: idToken,
            audience: process.env.GOOGLE_CLIENT_ID, // Use the same client ID that generated the token
        });

        const payload = ticket.getPayload();
        const { sub: googleId, email, name } = payload; // 'sub' is Google's unique ID for the user

        // 2. Find or Create Teacher in your database
        let teacher = await Teacher.findOne({
            $or: [
                { googleId: googleId }, // Check if already registered with Google
                { email: email }         // Check if email already exists (might be existing email/password user)
            ]
        });

        if (teacher) {
            // User exists
            // If they registered with email/password and now log in with Google,
            // link their Google ID if not already linked.
            if (!teacher.googleId) {
                teacher.googleId = googleId;
                await teacher.save({ validateBeforeSave: false }); // No password change, so skip validation
            }
            // Ensure email is verified if logging in via Google
            if (!teacher.isVerified) {
                teacher.isVerified = true;
                teacher.verificationToken = undefined;
                await teacher.save({ validateBeforeSave: false });
            }

        } else {
            // New user via Google
            // Create a new teacher record
            teacher = new Teacher({
                email: email,
                googleId: googleId,
                name: name || email, // Use name from Google, fallback to email
                isVerified: true, // Google accounts are implicitly verified
                // No password needed for Google-only sign-ups
            });
            await teacher.save(); // This will not hash a password, as none is provided.
        }

        // 3. Generate JWT for the authenticated teacher
        const token = jwt.sign(
            { id: teacher._id },
            process.env.JWT_SECRET,
            { expiresIn: "1h" }
        );

        // 4. Send success response with token and user info
        res.status(200).json({
            success: true,
            message: "Google login successful!",
            token,
            userId: teacher._id,
            email: teacher.email,
            sessionCode: 'default_session_code' // Placeholder
        });

    } catch (error) {
        console.error('Google login backend error:', error);
        if (error.code === 'ERR_INVALID_ARG_VALUE') {
            return res.status(401).json({ success: false, message: 'Invalid Google ID token. Please try again.' });
        }
        res.status(500).json({ success: false, message: 'Server error during Google login.' });
    }
};

// Verify Email Address
const verifyEmail = async (req, res) => {
    const { token } = req.query;

    if (!token) {
        return res.status(400).json({ success: false, message: 'No verification token provided.' });
    }

    const hashedToken = crypto
        .createHash('sha256')
        .update(token)
        .digest('hex');

    try {
        const teacher = await Teacher.findOne({ verificationToken: hashedToken });

        if (!teacher) {
            return res.status(400).json({ success: false, message: 'Invalid or expired verification link.' });
        }

        teacher.isVerified = true;
        teacher.verificationToken = undefined;

        await teacher.save();

        res.status(200).json({ success: true, message: 'Email verified successfully! You can now log in.' });
    } catch (error) {
        console.error('Email verification error:', error);
        res.status(500).json({ success: false, message: 'Server error during email verification.' });
    }
};


// Request Password Reset Link
const forgotPassword = async (req, res) => {
    const { email } = req.body;

    if (!email) {
        return res.status(400).json({ success: false, message: 'Please provide an email address.' });
    }

    try {
        const teacher = await Teacher.findOne({ email });

        if (!teacher) {
            console.log(`Forgot password requested for non-existent email: ${email}`);
            return res.status(200).json({
                success: true,
                message: 'If an account with that email exists, a password reset link has been sent to your inbox.'
            });
        }

        const resetToken = teacher.getResetPasswordToken();
        await teacher.save({ validateBeforeSave: false });

        const emailResult = await sendPasswordResetEmail(teacher.email, resetToken);

        if (!emailResult.success) {
            console.error(`Error sending password reset email to ${teacher.email}:`, emailResult.error);
            return res.status(200).json({
                success: true,
                message: 'If an account with that email exists, a password reset link has been sent to your inbox, though there was an issue sending the email.'
            });
        }

        res.status(200).json({
            success: true,
            message: 'If an account with that email exists, a password reset link has been sent to your inbox.'
        });

    } catch (error) {
        console.error('Forgot password error:', error);
        res.status(500).json({ success: false, message: 'Server error. Please try again later.' });
    }
};

// Reset Password
const resetPassword = async (req, res) => {
    const { token, newPassword } = req.body;

    if (!token || !newPassword) {
        return res.status(400).json({ success: false, message: 'Token and new password are required.' });
    }

    const hashedToken = crypto
        .createHash('sha256')
        .update(token)
        .digest('hex');

    try {
        const teacher = await Teacher.findOne({
            resetPasswordToken: hashedToken,
            resetPasswordExpires: { $gt: Date.now() }
        });

        if (!teacher) {
            return res.status(400).json({ success: false, message: 'Invalid or expired password reset link.' });
        }

        if (newPassword.length < 6) {
            return res.status(400).json({ success: false, message: 'New password must be at least 6 characters long.' });
        }

        teacher.password = newPassword;
        teacher.resetPasswordToken = undefined;
        teacher.resetPasswordExpires = undefined;

        await teacher.save();

        res.status(200).json({ success: true, message: 'Password reset successfully. You can now log in with your new password.' });

    } catch (error) {
        console.error('Reset password error:', error);
        res.status(500).json({ success: false, message: 'Server error. Please try again later.' });
    }
};

// Export all the functions
module.exports = {
    register,
    login,
    googleLogin, // <-- NEW EXPORT
    verifyEmail,
    forgotPassword,
    resetPassword
};